### ISSUE TITLE
CCF partition support has some bug in the new version of chrome plugin

### ISSUE THREAD

**Issue by Lovestarni** [Nixiak-nan/show_ranking#11]
![image](https://user-images.githubusercontent.com/19560284/140001955-c63efb35-004f-4117-976d-f41188f1e678.png)
It return no results when select the ccf rank option. It occur both on macos12 and win10.

**Comment by Nixiak-nan** [comment]
感谢您的反馈。经过作者测试，确实存在这个BUG，原因是因为作者的疏忽大意，不小心多删了一个名为dblp.js的文件，导致选择ccf选项时候报错。现已经修复此BUG，并已经提交至谷歌商店审核，预计两天后审核通过，如果着急使用的话，可以通过下载源码并离线安装。感谢您的反馈，祝您生活愉快。

**Comment by Lovestarni** [comment]
十分感谢
